; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting  
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
build_flags = -Wall -Wextra 
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps = 
	robtillaart/CRC@^1.0.3
	blynkkk/Blynk@^1.3.2
	adafruit/Adafruit SSD1306@^2.5.13
	suculent/AESLib@^2.3.6
	adafruit/Adafruit BMP3XX Library@^2.1.6
	;iavorvel/MyLD2410@^1.2.5
	;ayushsharma82/ElegantOTA@^3.1.7
	
